[tools]
# renovate: datasource=github-tags depName=go extractVersion=^go(?<version>.+)$
go = "1.26.2"

# renovate: datasource=github-releases depName=kubernetes-sigs/kind
kind = "0.27.0"

# renovate: datasource=github-releases depName=kubernetes/kubectl extractVersion=^v(?<version>.+)$
kubectl = "1.34.0"

# renovate: datasource=github-releases depName=helm/helm
helm = "3.18.0"

# renovate: datasource=github-releases depName=dapr/cli
"aqua:dapr/cli" = "1.15.1"

[settings]
experimental = true
