apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-values
spec:
  selector:
    matchLabels:
      app: read-values
  template:
    metadata:
      labels:
        app: read-values
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "read-values"
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: read-values
          image: andriykalashnykov/dapr-go-read-values:v0.0.1
          env:
            - name: DAPR_PORT
              value: "50001"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: read-values-svc
spec:
  selector:
    app: read-values
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
spec:
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
        - name: subscriber
          image: andriykalashnykov/dapr-go-subscriber:v0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: subscriber-svc
spec:
  selector:
    app: subscriber
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-values
spec:
  selector:
    matchLabels:
      app: write-values
  template:
    metadata:
      labels:
        app: write-values
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "write-values"
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: write-values
          image: andriykalashnykov/dapr-go-write-values:v0.0.1
          env:
            - name: DAPR_PORT
              value: "50001"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: write-values-svc
spec:
  selector:
    app: write-values
  ports:
    - port: 80
      targetPort: 8080
