apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendsvc
  labels:
    app: frontendsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendsvc
  template:
    metadata:
      labels:
        app: frontendsvc
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frontendsvc"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
    spec:
      containers:
        - name: frontendsvc
          image: ko.local/dapr-go-frontendsvc:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontendsvc
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer