apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: notifications-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    # https://docs.dapr.io/operations/components/component-secrets
    - name: redisHost
      value: redis-master.dapr-go.svc.cluster.local:6379
    - name: redisPassword
      value: RedisPassword
#      secretKeyRef:
#        name: redis
#        key: redis-password
auth:
  secretStore: kubernetes